#!/bin/bash

ps waux | grep node | grep -v grep

echo "starting ..."
## note: start as root, pass env vars to sudo param, this app will downgrade itself once it has initialized
sudo -E forever app.js &> log.txt &


cd etherpad-lite/node
forever server.js &> log.txt &
cd ../..

sleep 3
ps waux | grep node | grep -v grep

